[package]
name = "beveam"
version = "0.1.0"
edition = "2024"
default-run = "beveam"

[[bin]]
name = "beveam"
path = "src/main.rs"

[[bin]]
name = "check_js"
path = "src/bin/check_js.rs"

[dependencies]
bevy = "0.16.1"
boa_engine = "0.20.0"
once_cell = "1.21.3"
