version: '3'

tasks:
  build-systems:
    desc: Build Gleam project
    dir: systems
    cmds:
      - gleam build

  build-bun:
    desc: Run Bun build script
    cmds:
      - bun build ./systems/build/dev/javascript/systems/systems.mjs --outfile assets/scripts/systems.txt --minify-syntax --minify-whitespace

  prepare:
    desc: Run Rust prepare binary
    cmds:
      - cargo run --bin prepare

  all:
    desc: Run everything when systems/ changes
    deps: [build-systems, build-bun, prepare]
    sources:
      - systems/src/**/*.gleam
    watch: true
